# **HOW TO EXTRACT DATA THROUGH API**

In [3]:
import pandas as pd
import requests
#in this we extracted a api request from a movies website , through provided api key
#We will extract only those columns which are useful for us , we will not extract unnecessary ones

In [5]:
response = requests.get('https://api.themoviedb.org/3/movie/550/recommendations?language=en-US&page=1&api_key=683c572d766157aedff1dc7d2890ea7a')

In [12]:
df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_count']]

in this by .json we converted the data in frames by using dataframes , and the list inside list that we used was for the columns that we need

In [14]:
df = pd.DataFrame()

In [ ]:
#created a empty dataframe , as number of pages are 17 , and we only fetched data of page 1 , we need a loop to run through 17 pages

In [21]:
for i in range(1,18):
  response = requests.get('https://api.themoviedb.org/3/movie/550/recommendations?language=en-US&page={}&api_key=683c572d766157aedff1dc7d2890ea7a'.format(i))
  temp_df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_count']]
  df = pd.concat([df,temp_df], ignore_index = True)

In [22]:
df

,id,title,overview,release_date,popularity,vote_count
0,265349,Charlie's Country,"Blackfella Charlie is getting older, and he's ...",2013-10-12,1.3110,56
1,10990,Mulholland Falls,"In 1950s Los Angeles, a special crime squad of...",1996-04-26,4.8350,331
2,174344,Whitewash,"In the harsh, wintry woods of rural Quebec, Br...",2013-04-19,0.9434,44
3,11705,Red Road,"Jackie is a CCTV operator. One day, a man show...",2006-10-27,1.9705,225
4,251421,Private Property,A hoodlum plots to seduce a lonely housewife a...,1960-01-20,1.1045,48
...,...,...,...,...,...,...
342,251421,Private Property,A hoodlum plots to seduce a lonely housewife a...,1960-01-20,1.1045,48
343,10711,French Connection II,"""Popeye"" Doyle travels to Marseilles to find A...",1975-05-18,4.1997,486
344,46989,Blue Car,Meg is a gifted but emotionally scarred 18-yea...,2003-04-25,1.6300,57
345,1439930,The Punisher: One Last Kill,As Frank Castle searches for meaning beyond re...,2026-05-12,68.4245,2115
346,311,Once Upon a Time in America,A former Prohibition-era Jewish gangster retur...,1984-05-23,22.5546,6162

In [23]:
df.shape

(347, 6)

In [25]:
df.to_csv('movies.csv')

,Unnamed: 0,id,title,overview,release_date,popularity,vote_count
0,0,265349,Charlie's Country,"Blackfella Charlie is getting older, and he's ...",2013-10-12,1.3110,56
1,1,10990,Mulholland Falls,"In 1950s Los Angeles, a special crime squad of...",1996-04-26,4.8350,331
2,2,174344,Whitewash,"In the harsh, wintry woods of rural Quebec, Br...",2013-04-19,0.9434,44
3,3,11705,Red Road,"Jackie is a CCTV operator. One day, a man show...",2006-10-27,1.9705,225
4,4,251421,Private Property,A hoodlum plots to seduce a lonely housewife a...,1960-01-20,1.1045,48
...,...,...,...,...,...,...,...
342,342,251421,Private Property,A hoodlum plots to seduce a lonely housewife a...,1960-01-20,1.1045,48
343,343,10711,French Connection II,"""Popeye"" Doyle travels to Marseilles to find A...",1975-05-18,4.1997,486
344,344,46989,Blue Car,Meg is a gifted but emotionally scarred 18-yea...,2003-04-25,1.6300,57
345,345,1439930,The Punisher: One Last Kill,As Frank Castle searches for meaning beyond re...,2026-05-12,68.4245,2115
346,346,311,Once Upon a Time in America,A former Prohibition-era Jewish gangster retur...,1984-05-23,22.5546,6162

In [ ]:
#We can fetch api through rapidai across different categories