**#When a website don't want us to have their data through api or anything , we have to hit there every page through web scrapping**

In [9]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

In [10]:
#You can't directly get by writing requests.get() , you have to use headers
headers={'User-Agent':'Mozilla/5.0 (Windows NT 6.3; Win 64 ; x64) AppleWebKit /537.36(KHTML , like Gecko) Chrome/80.0.3987.162 Safari/537.36'}
response  = requests.get('https://books.toscrape.com',headers = headers)
response.encoding = "utf-8"

webpage = response.text
soup = BeautifulSoup(webpage, "html.parser")


#We used encoding = utf-8 because in price it was decoding wrongly , that's why

In [11]:
#I tried to try it on ambitionbox.com but it didn't work because it's privacy is increased over the time , so i tried on a open site , who allows

In [12]:
webpage

'<!DOCTYPE html>\n<!--[if lt IE 7]>      <html lang="en-us" class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->\n<!--[if IE 7]>         <html lang="en-us" class="no-js lt-ie9 lt-ie8"> <![endif]-->\n<!--[if IE 8]>         <html lang="en-us" class="no-js lt-ie9"> <![endif]-->\n<!--[if gt IE 8]><!--> <html lang="en-us" class="no-js"> <!--<![endif]-->\n    <head>\n        <title>\n    All products | Books to Scrape - Sandbox\n</title>\n\n        <meta http-equiv="content-type" content="text/html; charset=UTF-8" />\n        <meta name="created" content="24th Jun 2016 09:29" />\n        <meta name="description" content="" />\n        <meta name="viewport" content="width=device-width" />\n        <meta name="robots" content="NOARCHIVE,NOCACHE" />\n\n        <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->\n        <!--[if lt IE 9]>\n        <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>\n        <![endif]-->\n\n        \n            <link rel="shortcut icon" href="static/oscar/favicon.ico" />\n        \n\n        \n        \n    \n    \n        <link rel="stylesheet" type="text/css" href="static/oscar/css/styles.css" />\n    \n    <link rel="stylesheet" href="static/oscar/js/bootstrap-datetimepicker/bootstrap-datetimepicker.css" />\n    <link rel="stylesheet" type="text/css" href="static/oscar/css/datetimepicker.css" />\n\n\n        \n        \n\n        \n\n        \n            \n            \n\n        \n    </head>\n\n    <body id="default" class="default">\n        \n        \n    \n    \n    <header class="header container-fluid">\n        <div class="page_inner">\n            <div class="row">\n                <div class="col-sm-8 h1"><a href="index.html">Books to Scrape</a><small> We love being scraped!</small>\n</div>\n\n                \n            </div>\n        </div>\n    </header>\n\n    \n    \n<div class="container-fluid page">\n    <div class="page_inner">\n        \n    <ul class="breadcrumb">\n        <li>\n            <a href="index.html">Home</a>\n        </li>\n        <li class="active">All products</li>\n    </ul>\n\n        <div class="row">\n\n            <aside class="sidebar col-sm-4 col-md-3">\n                \n                <div id="promotions_left">\n                    \n                </div>\n                \n    \n    \n        \n        <div class="side_categories">\n            <ul class="nav nav-list">\n                \n                    <li>\n                        <a href="catalogue/category/books_1/index.html">\n                            \n                                Books\n                            \n                        </a>\n\n                        <ul>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/travel_2/index.html">\n                            \n                                Travel\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/mystery_3/index.html">\n                            \n                                Mystery\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/historical-fiction_4/index.html">\n                            \n                                Historical Fiction\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/sequential-art_5/index.html">\n                            \n                                Sequential Art\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/classics_6/index.html">\n                            \n                                Classics\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/philosophy_7/index.html">\n                            \n                                Philosophy\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/romance_8/index.html">\n                            \n                                Romance\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/womens-fiction_9/index.html">\n                            \n                                Womens Fiction\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/fiction_10/index.html">\n                            \n                                Fiction\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/childrens_11/index.html">\n                            \n                                Childrens\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/religion_12/index.html">\n                            \n                                Religion\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/nonfiction_13/index.html">\n                            \n                                Nonfiction\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/music_14/index.html">\n                            \n                                Music\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/default_15/index.html">\n                            \n                                Default\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/science-fiction_16/index.html">\n                            \n                                Science Fiction\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/sports-and-games_17/index.html">\n                            \n                                Sports and Games\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/add-a-comment_18/index.html">\n                            \n                                Add a comment\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/fantasy_19/index.html">\n                            \n                                Fantasy\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/new-adult_20/index.html">\n                            \n                                New Adult\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/young-adult_21/index.html">\n                            \n                                Young Adult\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/science_22/index.html">\n                            \n                                Science\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/poetry_23/index.html">\n                            \n                                Poetry\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/paranormal_24/index.html">\n                            \n                                Paranormal\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/art_25/index.html">\n                            \n                                Art\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/psychology_26/index.html">\n                            \n                                Psychology\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/autobiography_27/index.html">\n                            \n                                Autobiography\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/parenting_28/index.html">\n                            \n                                Parenting\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/adult-fiction_29/index.html">\n                            \n                                Adult Fiction\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/humor_30/index.html">\n                            \n                                Humor\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/horror_31/index.html">\n                            \n                                Horror\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/history_32/index.html">\n                            \n                                History\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/food-and-drink_33/index.html">\n                            \n                                Food and Drink\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/christian-fiction_34/index.html">\n                            \n                                Christian Fiction\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/business_35/index.html">\n                            \n                                Business\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/biography_36/index.html">\n                            \n                                Biography\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/thriller_37/index.html">\n                            \n                                Thriller\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/contemporary_38/index.html">\n                            \n                                Contemporary\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/spirituality_39/index.html">\n                            \n                                Spirituality\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/academic_40/index.html">\n                            \n                                Academic\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/self-help_41/index.html">\n                            \n                                Self Help\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/historical_42/index.html">\n                            \n                                Historical\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/christian_43/index.html">\n                            \n                                Christian\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/suspense_44/index.html">\n                            \n                                Suspense\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/short-stories_45/index.html">\n                            \n                                Short Stories\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/novels_46/index.html">\n                            \n                                Novels\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/health_47/index.html">\n                            \n                                Health\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/politics_48/index.html">\n                            \n                                Politics\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/cultural_49/index.html">\n                            \n                                Cultural\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/erotica_50/index.html">\n                            \n                                Erotica\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/crime_51/index.html">\n                            \n                                Crime\n                            \n                        </a>\n\n                        </li>\n                        \n                            </ul></li>\n                        \n                \n            </ul>\n        </div>\n    \n    \n\n            </aside>\n\n            <div class="col-sm-8 col-md-9">\n                \n                <div class="page-header action">\n                    <h1>All products</h1>\n                </div>\n                \n\n                \n\n\n\n<div id="messages">\n\n</div>\n\n\n                <div id="promotions">\n                    \n                </div>\n\n                \n    <form method="get" class="form-horizontal">\n        \n        <div style="display:none">\n            \n            \n        </div>\n\n        \n            \n                \n                    <strong>1000</strong> results - showing <strong>1</strong> to <strong>20</strong>.\n                \n            \n            \n        \n    </form>\n    \n        <section>\n            <div class="alert alert-warning" role="alert"><strong>Warning!</strong> This is a demo website for web scraping purposes. Prices and ratings here were randomly assigned and have no real meaning.</div>\n\n            <div>\n                <ol class="row">\n                    \n              

In [13]:
soup = BeautifulSoup(webpage ,'lxml')
#lxml is built in the library , it makes parsing muche easy

In [14]:
print(soup.prettify())
#it basically shows like html code organised

<!DOCTYPE html>
<!--[if lt IE 7]>      <html lang="en-us" class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html lang="en-us" class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html lang="en-us" class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="en-us">
 <!--<![endif]-->
 <head>
  <title>
   All products | Books to Scrape - Sandbox
  </title>
  <meta content="text/html; charset=utf-8" http-equiv="content-type"/>
  <meta content="24th Jun 2016 09:29" name="created"/>
  <meta content="" name="description"/>
  <meta content="width=device-width" name="viewport"/>
  <meta content="NOARCHIVE,NOCACHE" name="robots"/>
  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
        <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
  <link href="static/oscar/favicon.ico" rel="shortcut icon"/>
  <link href="static/oscar/css/styles.css" rel="stylesheet" type="text/css"/>
  <link href="static/oscar/js/bootstrap-datetimepicker/bootstrap-datetimepicker.css" rel="stylesheet"/>
  <link href="static/oscar/css/datetimepicker.css" rel="stylesheet" type="text/css"/>
 </head>
 <body class="default" id="default">
  <header class="header container-fluid">
   <div class="page_inner">
    <div class="row">
     <div class="col-sm-8 h1">
      <a href="index.html">
       Books to Scrape
      </a>
      <small>
       We love being scraped!
      </small>
     </div>
    </div>
   </div>
  </header>
  <div class="container-fluid page">
   <div class="page_inner">
    <ul class="breadcrumb">
     <li>
      <a href="index.html">
       Home
      </a>
     </li>
     <li class="active">
      All products
     </li>
    </ul>
    <div class="row">
     <aside class="sidebar col-sm-4 col-md-3">
      <div id="promotions_left">
      </div>
      <div class="side_categories">
       <ul class="nav nav-list">
        <li>
         <a href="catalogue/category/books_1/index.html">
          Books
         </a>
         <ul>
          <li>
           <a href="catalogue/category/books/travel_2/index.html">
            Travel
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/mystery_3/index.html">
            Mystery
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/historical-fiction_4/index.html">
            Historical Fiction
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/sequential-art_5/index.html">
            Sequential Art
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/classics_6/index.html">
            Classics
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/philosophy_7/index.html">
            Philosophy
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/romance_8/index.html">
            Romance
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/womens-fiction_9/index.html">
            Womens Fiction
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/fiction_10/index.html">
            Fiction
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/childrens_11/index.html">
            Childrens
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/religion_12/index.html">
            Religion
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/nonfiction_13/index.html">
            Nonfiction
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/music_14/index.html">
            Music
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/default_15/index.html">
            Default
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/science-fiction_16/index.html">
            Science Fiction
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/sports-and-games_17/index.html">
            Sports and Games
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/add-a-comment_18/index.html">
            Add a comment
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/fantasy_19/index.html">
            Fantasy
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/new-adult_20/index.html">
            New Adult
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/young-adult_21/index.html">
            Young Adult
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/science_22/index.html">
            Science
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/poetry_23/index.html">
            Poetry
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/paranormal_24/index.html">
            Paranormal
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/art_25/index.html">
            Art
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/psychology_26/index.html">
            Psychology
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/autobiography_27/index.html">
            Autobiography
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/parenting_28/index.html">
            Parenting
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/adult-fiction_29/index.html">
            Adult Fiction
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/humor_30/index.html">
            Humor
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/horror_31/index.html">
            Horror
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/history_32/index.html">
            History
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/food-and-drink_33/index.html">
            Food and Drink
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/christian-fiction_34/index.html">
            Christian Fiction
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/business_35/index.html">
            Business
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/biography_36/index.html">
            Biography
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/thriller_37/index.html">
            Thriller
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/contemporary_38/index.html">
            Contemporary
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/spirituality_39/index.html">
            Spirituality
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/academic_40/index.html">
            Academic
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/self-help_41/index.html">
            Self Help
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/historical_42/index.html">
            Historical
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/christian_43/index.html">
            Christian
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/suspense_44/index.html">
            Suspense
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/short-stories_45/index.html">
            Short Stories
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/novels_46/index.html">
            Novels
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/health_47/index.html">
            Health
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/politics_48/index.html">
            Politics
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/cultural_49/index.html">
            Cultural
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/erotica_50/index.html">
            Erotica
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/crime_51/index.html">
            Crime
           </a>
          </li>
         </ul>
        </li>
       </ul>
      </div>
     </aside>
     <div class="col-sm-8 col-md-9">
      <div class="page-header action">
       <h1>
        All products
       </h1>
      </div>
      <div id="messages">
      </div>
      <div id="promotions">
      </div>
      <form class="form-horizontal" method="get">
       <div style="display:none">
       </div>
       <strong>
        1000
       </strong>
       results - showing
       <strong>
        1
       </strong>
       to
       <strong>
        20
       </strong>
       .
      </form>
      <section>
       <div class="alert alert-warning" role="alert">
        <strong>
         Warning!
        </strong>
        This is a demo website for web scraping purposes. Prices and ratings here were randomly assigned and have no real meaning.
       </div>
       <div>
        <ol class="row">
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/a-light-in-the-attic_1000/index.html">
             <img alt="A Light in the Attic" class="thumbnail" src="media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg"/>
            </a>
           </div>
           <p class="star-rating Three">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="catalogue/a-light-in-the-attic_1000/index.html" title="A Light in the Attic">
             A Light in the ...
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             £51.77
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/tipping-the-velvet_999/index.html">
             <img alt="Tipping the Velvet" class="thumbnail" src="media/cache/26/0c/260c6ae16bce31c8f8c95daddd9f4a1c.jpg"/>
            </a>
           </div>
           <p class="star-rating One">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="catalogue/tipping-the-velvet_999/index.html" title="Tipping the Velvet">
             Tipping the Velvet
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             £53.74
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/soumission_998/index.html">
             <img alt="Soumission" class="thumbnail" src="media/cache/3e/ef/3eef99c9d9adef34639f510662022830.jpg"/>
            </a>
           </div>
           <p class="star-rating One">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="catalogue/soumission_998/index.html" title="Soumission">
             Soumission
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             £50.10
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/sharp-objects_997/index.html">
             <img alt="Sharp Objects" class="thumbnail" src="media/cache/32/51/3251cf3a3412f53f339e42cac2134093.jpg"/>
            </a>
           </div>
           <p class="star-rating Four">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="catalogue/sharp-objects_997/index.html" title="Sharp Objects">
             Sharp Objects
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             £47.82
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/sapiens-a-brief-history-of-humankind_996/index.html">
             <img alt="Sapiens: A Brief History of Humankind" class="thumbnail" src="media/cache/be/a5/bea5697f2534a2f86a3ef27b5a8c12a6.jpg"/>
            </a>
           </div>
           <p class="star-rating Five">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="catalogue/sapiens-a-brief-history-of-humankind_996/index.html" title="Sapiens: A Brief History of Humankind">
             Sapiens: A Brief History ...
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             £54.23
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/the-requiem-red_995/index.html">
             <img alt="The Requiem Red" class="thumbnail" src="media/cache/68/33/68339b4c9bc034267e1da611ab3b34f8.jpg"/>
            </a>
           </div>
           <p class="star-rating One">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="catalogue/the-requiem-red_995/index.html" title="The Requiem Red">
             The Requiem Red
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             £22.65
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html">
             <img alt="The Dirty Little Secrets of Getting Your Dream Job" class="thumbnail" src="media/cache/92/27/92274a95b7c251fea59a2b8a78275ab4.jpg"/>
            </a>
           </div>
           <p class="star-rating Four">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html" title="The Dirty Little Secrets of Getting Your Dream Job">
             The Dirty Little Secrets ...
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             £33.34
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/the-coming-woman-a-novel-based-on-the-life-of-the-infamous-feminist-victoria-woodhull_993/index.html">
             <img alt="The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull" class="thumbnail" src="media/cache/3d/54/3d54940e57e662c4dd1f3ff00c78cc64.jpg"/>

In [15]:
soup.find_all('h1')[0].text

'All products'

In [16]:
len(soup.find_all('h3')) #for finding number of h3

20

In [17]:
for i in soup.find_all('h3'):
  print(i.text)

#sometimes in data in html format contains spaces , \n commands that python considers spaces next line
#to remove all of them just write i.text.strip()

A Light in the ...
Tipping the Velvet
Soumission
Sharp Objects
Sapiens: A Brief History ...
The Requiem Red
The Dirty Little Secrets ...
The Coming Woman: A ...
The Boys in the ...
The Black Maria
Starving Hearts (Triangular Trade ...
Shakespeare's Sonnets
Set Me Free
Scott Pilgrim's Precious Little ...
Rip it Up and ...
Our Band Could Be ...
Olio
Mesaerion: The Best Science ...
Libertarianism for Beginners
It's Only the Himalayas

In [18]:
for i in soup.find_all('p'):
  print(i.text.strip())

#this gives information about p tags - p tags were prices of the book and if they are in stock or not

£51.77
In stock

£53.74
In stock

£50.10
In stock

£47.82
In stock

£54.23
In stock

£22.65
In stock

£33.34
In stock

£17.93
In stock

£22.60
In stock

£52.15
In stock

£13.99
In stock

£20.66
In stock

£17.46
In stock

£52.29
In stock

£35.02
In stock

£57.25
In stock

£23.88
In stock

£37.59
In stock

£51.33
In stock

£45.17
In stock

In [19]:
#This gives information about all the p tags , but if i need only prices i have to use class of p tag
for i in soup.find_all('p',class_='price_color'):
  print(i.text.strip())

#this gives info only about the prices not in stock or not

£51.77
£53.74
£50.10
£47.82
£54.23
£22.65
£33.34
£17.93
£22.60
£52.15
£13.99
£20.66
£17.46
£52.29
£35.02
£57.25
£23.88
£37.59
£51.33
£45.17

This becomes hectic if we see heading by heading , or tags by tags , so it's better to see data for each book , that is correct method below

In [20]:
books =soup.find_all('article', class_='product_pod')

In [25]:
name = []
rating = []
price_color = []

for i in books :
  name.append(i.find('h3').text.strip())
  rating.append(i.find('p',class_ ='star-rating')['class'][1])
  price_color.append(i.find('p',class_='price_color').text.strip())



d = {'name':name , 'rating':rating , 'price_color':price_color }
df = pd.DataFrame(d)

#this class means class = star-rating three for ex, so class has star-rating and three as different indexes , 1 chooses second one that is three

#if i write name.append(print(i.find('h3').text.strip())) - it will return nothing it will just print the values so the title name will not get stored inside the list

In [22]:
price_color

['£51.77',
 '£53.74',
 '£50.10',
 '£47.82',
 '£54.23',
 '£22.65',
 '£33.34',
 '£17.93',
 '£22.60',
 '£52.15',
 '£13.99',
 '£20.66',
 '£17.46',
 '£52.29',
 '£35.02',
 '£57.25',
 '£23.88',
 '£37.59',
 '£51.33',
 '£45.17']

In [28]:
df

                                     name rating price_color
0                      A Light in the ...  Three      £51.77
1                      Tipping the Velvet    One      £53.74
2                              Soumission    One      £50.10
3                           Sharp Objects   Four      £47.82
4            Sapiens: A Brief History ...   Five      £54.23
5                         The Requiem Red    One      £22.65
6            The Dirty Little Secrets ...   Four      £33.34
7                 The Coming Woman: A ...  Three      £17.93
8                     The Boys in the ...   Four      £22.60
9                         The Black Maria    One      £52.15
10  Starving Hearts (Triangular Trade ...    Two      £13.99
11                  Shakespeare's Sonnets   Four      £20.66
12                            Set Me Free   Five      £17.46
13    Scott Pilgrim's Precious Little ...   Five      £52.29
14                      Rip it Up and ...   Five      £35.02
15                  Our Band Could Be ...  Three      £57.25
16                                   Olio    One      £23.88
17        Mesaerion: The Best Science ...    One      £37.59
18           Libertarianism for Beginners    Two      £51.33
19                It's Only the Himalayas    Two      £45.17

In [33]:
final = pd.DataFrame()

for j in range (1,51):
  url = 'https://books.toscrape.com/catalogue/page-{}.html'.format(j)

  headers={'User-Agent':'Mozilla/5.0 (Windows NT 6.3; Win 64 ; x64) AppleWebKit /537.36(KHTML , like Gecko) Chrome/80.0.3987.162 Safari/537.36'}
  response  = requests.get(url,headers = headers)
  response.encoding = "utf-8"

  webpage = response.text
  soup = BeautifulSoup(webpage, "html.parser")
  soup = BeautifulSoup(webpage ,'lxml')

  books = soup.find_all('article', class_='product_pod')

  name = []
  rating = []
  price_color = []

  for i in books :
    name.append(i.find('h3').text.strip())
    rating.append(i.find('p',class_ ='star-rating')['class'][1])
    price_color.append(i.find('p',class_='price_color').text.strip())



  d = {'name':name , 'rating':rating , 'price_color':price_color }
  df = pd.DataFrame(d)

  final = pd.concat([final,df],ignore_index=True)

In [34]:
final

                                 name rating price_color
0                  A Light in the ...  Three      £51.77
1                  Tipping the Velvet    One      £53.74
2                          Soumission    One      £50.10
3                       Sharp Objects   Four      £47.82
4        Sapiens: A Brief History ...   Five      £54.23
..                                ...    ...         ...
995  Alice in Wonderland (Alice's ...    One      £55.53
996    Ajin: Demi-Human, Volume 1 ...   Four      £57.06
997         A Spy's Devotion (The ...   Five      £16.97
998           1st to Die (Women's ...    One      £53.98
999           1,000 Places to See ...   Five      £26.08

[1000 rows x 3 columns]

Finally if i need to convert ratings into numeric , i can create a dictionary for mapping